# Add 'core' to any changes within 'com.unity.render-pipelines.core' folder or any subfolders
core:
  - com.unity.render-pipelines.core/**/*
  - TestProjects/SRP*/**/*
  
# Add 'hdrp' to any changes within HDRP-related folder or any subfolders
hdrp:
  - com.unity.render-pipelines.high-definition-config/**/*
  - com.unity.render-pipelines.high-definition/**/*
  - com.unity.testing.hdrp/**/*
  - TestProjects/HDRP*/**/*
  
universal:
  - com.unity.render-pipelines.universal/**/*
  - com.unity.render-pipelines.lightweight/**/*
  - TestProjects/Universal*/**/*
  
shadergraph:
  - com.unity.shadergraph/**/*
  - TestProjects/ShaderGraph*/**/*
  
vfxgraph:
  - com.unity.visualeffectgraph/**/*
  - com.unity.testing.visualeffectgraph/**/*
  - TestProjects/VisualEffectGraph*/**/*
  
yamato:
  - .yamato/*
  
testing:
  - TestProjects/**/*