name: Branch naming rules
on: create

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: deepakputhraya/action-branch-name@master
      with:
        regex: '([a-z])+\/([a-z])+' # Regex the branch should match. This enforces grouping
        allowed_prefixes: 'feature,release,srp,universal,hdrp,vfx,bugfix,bug-fix,fix' # All branches should start with the given prefix
