name: Run tests on PR

on: pull_request
    
jobs:
  build:
    
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@master
    
    - name: Print Pull Request Branch name extracted from GitHub context
      env:
        BRNAME: ${{ github.head_ref }}
      run: echo "Branch name = $BRNAME"
    
    - uses: actions/setup-python@v1
      with:
       python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
       architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      
    - name: Run SRP ABV
      run: python .yamato/start-abv.py "${{ github.head_ref }}" "${{ github.sha }}" "${{ secrets.Yamato }}"
